---
root: true

parserOptions:
  ecmaVersion: 2019
  sourceType: module

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended
  - prettier
  - prettier/react
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript

plugins:
  - react
  - react-hooks
  - import
  - prettier

settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.tsx', '.jsx']
  react:
    version: detect

env:
  es6: true
  browser: true
  node: true

rules:
  no-use-before-define: 0
  import/no-extraneous-dependencies: off
  eol-last: ['error', 'always']
  import/extensions: off
  import/default: off
  no-shadow: 0
  no-unused-vars: 0
  prefer-destructuring: 0
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  react/require-default-props: off
  react/no-unused-prop-types: warn
  object-shorthand: warn
  # no-debugger: warn
