name: main.yml
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: "."
          git-user: redkubesbot
          git-password: ${{ secrets.GH_TOKEN }}
          deployment-branch: gh-pages
