name: main.yml
on:
  push:
    branches: [master]
env:
  GIT_USER: redkubesbot
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Deploy
        run: |
          git config --global user.email "redkubesbot@users.noreply.github.com"
          git config --global user.name "redkubesbot"
          echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
          npm install && npm run deploy
