name: main.yml
env:
  GIT_USER: redkubesbot
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docusaurus Deployment
        run: npm run deploy
